export const tagTypes: Record<string, string> = {
  auth: "auth",
  user: "users",
  assigen_pricing_features: "assigen-pricing-features",
  business_we_cover: "business-we-cover",
  categories: "categories",
  pricing_category: "pricing-category",
  pricing_features: "pricing-features",
  pricings: "pricings",
  services: "services",
  why_choose_us: "why-choose-us",
  subscriptions: "subscriptions",
  divisions: "divisions",
  districts: "districts",
  upzelas: "upzelas",
  service_videos:"service-videos",
  heroes:"heroes",
  who_we_are:"who-we-are",
  who_we_are_features:"who-we-are-features",
  video_reviews:"video-reviews",
  testimonials:"testimonials",
  teams:"teams",
  portfolio_categories:"portfolio-categories",
  portfolio:"portfolio",
  portfolio_details:"portfolio-details",
  blog_categories:"blog-categories",
  blogs:"blogs",
  blog_details:"blog-details",
  video_gallery_categories:"video-gallary-categories",
  video_gallery:"video-gallery",
  photo_gallery_categories:"photo-gallery-categories",
  photo_gallaries:"photo-gallaries",
  photo_gallery_album:"photo-gallery-album",
  send_massage:'send-massage',

};

export const tagTypesList: string[] = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.assigen_pricing_features,
  tagTypes.business_we_cover,
  tagTypes.categories,
  tagTypes.pricing_category,
  tagTypes.pricing_features,
  tagTypes.pricings,
  tagTypes.services,
  tagTypes.why_choose_us,
  tagTypes.subscriptions,
  tagTypes.divisions,
  tagTypes.districts,
  tagTypes.upzelas,
  tagTypes.service_videos,
  tagTypes.heroes,
  tagTypes.who_we_are,
  tagTypes.who_we_are_features,
  tagTypes.video_reviews,
  tagTypes.testimonials,
  tagTypes.teams,
  tagTypes.portfolio_categories,
  tagTypes.portfolio,
  tagTypes.portfolio_details,
  tagTypes.blog_categories,
  tagTypes.blogs,
  tagTypes.blog_details,
  tagTypes.video_gallery_categories,
  tagTypes.video_gallery,
  tagTypes.photo_gallery_categories,
  tagTypes.photo_gallaries,
  tagTypes.photo_gallery_album,
  tagTypes.send_massage,

];
